// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmfsubnfjpovhmhpvwmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZnN1Ym5manBvdmhtaHB2d21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTUwNTMsImV4cCI6MjA3MTk3MTA1M30.9djp_aaK8hFhRz_4ocVoM6zNlTiihCH3CsFCyHxHgis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});